export const VIEWS = {
  LOGIN: 'LOGIN',
  TWOFACTOR: 'TWOFACTOR',
  REGISTER: 'REGISTER',
  VERIFY_NEW_USER: 'VERIFY_NEW_USER',
  ADDGOOGLEAUTH: 'ADDGOOGLEAUTH',
  FORGOTPASSWORD: 'FORGOTPASSWORD',
  RESETPASSWORD: 'RESETPASSWORD'
} as const
