export const STEPS_LOGIN = {
  LOGIN: 'LOGIN',
  TWOFACTOR: 'TWOFACTOR',
  RESETPASSWORD: 'RESETPASSWORD',
  ADDGOOGLEAUTH: 'ADDGOOGLEAUTH'
} as const

export const STEPS_REGISTER = {
  REGISTER: 'REGISTER',
  VERIFY_NEW_USER: 'VERIFY_NEW_USER',
  ADDGOOGLEAUTH: 'ADDGOOGLEAUTH'
}
